CREATE SCHEMA IF NOT EXISTS codeShieldDB

CREATE TABLE IF NOT EXISTS users (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS task (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    assignee_id BIGINT,
    created_at TIMESTAMP,
    description VARCHAR(255),
    due_date TIMESTAMP,
    status VARCHAR(50),
    title VARCHAR(255)
);